//! The ensure DDL, pinned as data.
//!
//! Ensuring a table used to be a loop that built each statement and awaited it
//! immediately, so the only way to see what it emits was to run it against a
//! server — and nothing pinned the text. These cells compare the rendered
//! sequence itself, in order, with no connection anywhere: a reordering, a
//! dropped `IF NOT EXISTS`, a changed type mapping or a lost `CACHE 32` all
//! fail here rather than silently changing what a user's database gets.

use rdlt_connector::core::{
    ColumnDef, ColumnType, LogicalType, PipelineId, Provenance, TableName, TableSchema, WriteMode,
};
use rdlt_connector_postgres::dest::sqlgen::{ensure_merge_sql, ensure_table_sql};
use rdlt_connector_postgres::dest::{DestinationOptions, MergeStrategy};

fn col(name: &str, scalar: LogicalType, nullable: bool) -> ColumnDef {
    ColumnDef {
        name: name.to_owned(),
        column_type: ColumnType::Scalar { scalar },
        nullable,
        provenance: Provenance::Inferred,
    }
}

fn schema(table: &str, columns: Vec<ColumnDef>) -> TableSchema {
    TableSchema {
        table: TableName::from(table),
        parent: None,
        columns,
    }
}

fn events() -> TableSchema {
    schema(
        "events",
        vec![
            col("id", LogicalType::Int64, false),
            col("note", LogicalType::Utf8, true),
        ],
    )
}

fn pipeline() -> PipelineId {
    PipelineId::from("p")
}

/// Options carrying one explicit strategy — the field is set at construction
/// so the value is visible where the options are made, not two lines later.
fn with_strategy(strategy: MergeStrategy) -> DestinationOptions {
    DestinationOptions {
        merge_strategy: Some(strategy),
        ..DestinationOptions::default()
    }
}

fn merge_by_id() -> WriteMode {
    WriteMode::Merge {
        key: vec!["id".to_owned()],
    }
}

#[test]
fn append_ensures_only_the_target_leg() {
    // No stage table for a non-merge mode: an UNLOGGED twin and its sequence
    // would be created, written and truncated for nothing.
    assert_eq!(
        ensure_table_sql(&pipeline(), &events(), &WriteMode::Append, None),
        vec![
            "CREATE TABLE IF NOT EXISTS \"events\" (\"id\" BIGINT NOT NULL, \"note\" TEXT)",
            "ALTER TABLE \"events\" ADD COLUMN IF NOT EXISTS \"id\" BIGINT",
            "ALTER TABLE \"events\" ADD COLUMN IF NOT EXISTS \"note\" TEXT",
        ]
    );
}

#[test]
fn merge_ensures_a_stage_leg_with_a_cached_arrival_sequence() {
    let sql = ensure_table_sql(&pipeline(), &events(), &merge_by_id(), None);
    // The target leg first, then the stage leg — order is part of the pin.
    assert_eq!(
        sql[0],
        "CREATE TABLE IF NOT EXISTS \"events\" (\"id\" BIGINT NOT NULL, \"note\" TEXT)"
    );
    let stage_create = sql
        .iter()
        .find(|s| s.starts_with("CREATE UNLOGGED"))
        .expect("a stage leg exists under merge");
    // UNLOGGED, nullability dropped on the stage, and the arrival column
    // carrying its measured cache — 122 ms of a 642 ms stage COPY.
    assert!(stage_create.contains("CREATE UNLOGGED TABLE IF NOT EXISTS"));
    assert!(stage_create.contains("\"id\" BIGINT, \"note\" TEXT"));
    assert!(
        stage_create
            .contains("\"__rdlt_arrival\" bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 32)"),
        "the arrival sequence must stay an identity column with CACHE 32: {stage_create}"
    );
}

#[test]
fn a_widened_column_adds_a_using_cast_after_its_add() {
    // The widen is a WITHIN-SESSION rule: it fires from the schema this
    // session last ensured, not from the live catalog.
    let before = schema("events", vec![col("id", LogicalType::Int64, false)]);
    let after = schema("events", vec![col("id", LogicalType::Utf8, false)]);
    let sql = ensure_table_sql(&pipeline(), &after, &WriteMode::Append, Some(&before));
    assert_eq!(
        sql,
        vec![
            "CREATE TABLE IF NOT EXISTS \"events\" (\"id\" TEXT NOT NULL)",
            "ALTER TABLE \"events\" ADD COLUMN IF NOT EXISTS \"id\" TEXT",
            "ALTER TABLE \"events\" ALTER COLUMN \"id\" TYPE TEXT USING \"id\"::TEXT",
        ]
    );
}

#[test]
fn an_unchanged_column_is_added_but_never_widened() {
    let same = events();
    let sql = ensure_table_sql(&pipeline(), &same, &WriteMode::Append, Some(&same));
    assert!(
        !sql.iter().any(|s| s.contains("ALTER COLUMN")),
        "nothing changed type, so nothing may be widened: {sql:?}"
    );
}

#[test]
fn upsert_ensures_a_unique_index_that_carries_its_key_columns() {
    // Upsert must be asked for: the DEFAULT strategy is delete-insert, whose
    // index is a plain supporting one — there is no arbiter to enforce.
    let options = with_strategy(MergeStrategy::Upsert);
    let stmts = ensure_merge_sql(&options, &events(), &merge_by_id()).expect("valid options");
    let unique: Vec<_> = stmts.iter().filter(|s| s.1.is_some()).collect();
    assert_eq!(unique.len(), 1, "one arbiter index: {stmts:?}");
    assert_eq!(unique[0].1.as_deref(), Some(&["id".to_owned()][..]));
    assert!(
        unique[0].0.contains("CREATE UNIQUE INDEX IF NOT EXISTS"),
        "{:?}",
        unique[0].0
    );
}

#[test]
fn scd2_ensures_both_validity_columns_before_any_index() {
    let options = with_strategy(MergeStrategy::Scd2);
    let stmts = ensure_merge_sql(&options, &events(), &merge_by_id()).expect("valid options");
    let texts: Vec<&str> = stmts.iter().map(|s| s.0.as_str()).collect();
    let from = texts
        .iter()
        .position(|s| s.contains("_rdlt_valid_from"))
        .expect("valid_from column");
    let to = texts
        .iter()
        .position(|s| s.contains("_rdlt_valid_to"))
        .expect("valid_to column");
    let first_index = texts
        .iter()
        .position(|s| s.contains("INDEX"))
        .unwrap_or(usize::MAX);
    assert!(
        from < to,
        "valid_from is emitted before valid_to: {texts:?}"
    );
    assert!(
        to < first_index,
        "validity columns precede the index plan: {texts:?}"
    );
    // NOT NULL DEFAULT now() on valid_from only — valid_to's openness is the
    // marker an active row carries.
    assert!(texts[from].contains("TIMESTAMPTZ NOT NULL DEFAULT now()"));
    assert!(texts[to].ends_with("TIMESTAMPTZ"));
}

#[test]
fn the_default_strategy_ensures_a_plain_supporting_index() {
    // delete-insert needs the key indexed to find rows, but must NOT declare
    // it unique — duplicates are resolved by the plan, not refused by the
    // database.
    let stmts = ensure_merge_sql(&DestinationOptions::default(), &events(), &merge_by_id())
        .expect("valid options");
    assert_eq!(stmts.len(), 1, "one supporting index: {stmts:?}");
    assert!(stmts[0].1.is_none(), "not a unique index: {stmts:?}");
    assert!(stmts[0].0.starts_with("CREATE INDEX IF NOT EXISTS"));
}

#[test]
fn a_non_merge_mode_emits_no_merge_statements_and_still_validates() {
    let options = DestinationOptions::default();
    let stmts = ensure_merge_sql(&options, &events(), &WriteMode::Append)
        .expect("default options are valid");
    assert!(
        stmts.is_empty(),
        "nothing to ensure beyond the table: {stmts:?}"
    );
}

#[test]
fn merge_only_options_are_refused_under_append_with_the_shared_error() {
    // The rule set is sqlcore's; this pins that the postgres path still runs
    // it, and still runs it AFTER the tables exist.
    let options = with_strategy(MergeStrategy::Upsert);
    let err = ensure_merge_sql(&options, &events(), &WriteMode::Append)
        .expect_err("a merge strategy under Append is a config error");
    assert!(
        format!("{err}").contains("events"),
        "the error names the table: {err}"
    );
}
