[package]
name = "rdlt-cli"
description = "rdlt dev CLI: TOML pipeline spec -> run -> report"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "rdlt"
path = "src/main.rs"

[dependencies]
libc = "0.2"
rdlt = { workspace = true, features = ["rest", "duckdb", "postgres", "file", "parquet", "postgres-source", "iceberg"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
serde_yaml = { workspace = true }

[lints]
workspace = true
