//! The form of each message of the protocol: its size in memory, and the kind of each of its
//! fields, from which `rdlt-wire` bounds what a message decodes to before decoding it.

use std::fmt::Write as _;

use protox::prost_reflect::prost_types::field_descriptor_proto::{Label, Type};
use protox::prost_reflect::prost_types::{
    DescriptorProto, FieldDescriptorProto, FileDescriptorSet,
};

/// A message the forms cannot describe.
#[derive(Debug)]
enum Unformed {
    /// A field is a group, which the protocol does not use.
    Group(String),
    /// A field's message is not one of the package's own.
    Foreign(String),
}

impl std::fmt::Display for Unformed {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Group(field) => write!(formatter, "field {field} is a group"),
            Self::Foreign(name) => write!(formatter, "{name} is no message of the package's own"),
        }
    }
}

impl std::error::Error for Unformed {}

/// The package every message is in.
const PACKAGE: &str = ".rdlt.connector.v1.";

/// The Rust code of the forms of the messages `descriptors` describes, and of what each method
/// of the service takes and answers.
pub(crate) fn forms(descriptors: &FileDescriptorSet) -> Result<String, anyhow::Error> {
    let mut code = String::from(
        "// Generated by `cargo xtask codegen` from the protocol's `.proto` files.\n\n\
         use super::{Field, Form, Kind};\nuse crate::v1;\n",
    );
    let mut messages: Vec<&DescriptorProto> = descriptors
        .file
        .iter()
        .flat_map(|file| &file.message_type)
        .collect();
    messages.sort_by_key(|message| message.name());
    for message in messages {
        form(&mut code, message)?;
    }
    let methods: Vec<_> = descriptors
        .file
        .iter()
        .flat_map(|file| &file.service)
        .flat_map(|service| &service.method)
        .collect();
    for (function, what) in [("request", "takes"), ("response", "answers")] {
        writeln!(
            code,
            "\n/// The form of what the method `method` {what}.\n\
             pub fn {function}(method: &str) -> Option<&'static Form> {{\n    \
             match method {{"
        )?;
        for method in &methods {
            let type_name = if function == "request" {
                method.input_type()
            } else {
                method.output_type()
            };
            writeln!(
                code,
                "        {:?} => Some(&{}),",
                method.name(),
                constant(local(type_name)?)
            )?;
        }
        code.push_str("        _ => None,\n    }\n}\n");
    }
    Ok(code)
}

/// Writes `message`'s form to `code`.
fn form(code: &mut String, message: &DescriptorProto) -> anyhow::Result<()> {
    let name = message.name();
    let mut fields: Vec<&FieldDescriptorProto> = message.field.iter().collect();
    fields.sort_by_key(|field| field.number());
    writeln!(
        code,
        "\n/// The form of `{name}`.\npub(crate) static {}: Form = Form {{\n    \
         name: {name:?},\n    size: size_of::<v1::{name}>(),\n    fields: &[",
        constant(name)
    )?;
    for field in fields {
        writeln!(
            code,
            "        Field {{ number: {}, kind: {}, repeated: {} }},",
            field.number(),
            kind(field)?,
            field.label() == Label::Repeated
        )?;
    }
    code.push_str("    ],\n};\n");
    Ok(())
}

/// The kind of `field`, as the form's code writes it.
fn kind(field: &FieldDescriptorProto) -> Result<String, anyhow::Error> {
    Ok(match field.r#type() {
        Type::Message => format!("Kind::Message(&{})", constant(local(field.type_name())?)),
        Type::String => "Kind::String".to_owned(),
        Type::Bytes => "Kind::Bytes".to_owned(),
        Type::Bool => "Kind::Scalar(1)".to_owned(),
        Type::Int32
        | Type::Uint32
        | Type::Sint32
        | Type::Fixed32
        | Type::Sfixed32
        | Type::Float
        | Type::Enum => "Kind::Scalar(4)".to_owned(),
        Type::Int64
        | Type::Uint64
        | Type::Sint64
        | Type::Fixed64
        | Type::Sfixed64
        | Type::Double => "Kind::Scalar(8)".to_owned(),
        Type::Group => return Err(Unformed::Group(field.name().to_owned()).into()),
    })
}

/// The name of the message `type_name` names within the package.
fn local(type_name: &str) -> Result<&str, anyhow::Error> {
    type_name
        .strip_prefix(PACKAGE)
        .filter(|name| !name.contains('.'))
        .ok_or_else(|| Unformed::Foreign(type_name.to_owned()).into())
}

/// The constant naming the form of `message`: its name in capitals, words parted by `_`.
fn constant(message: &str) -> String {
    let mut name = String::new();
    for (index, c) in message.chars().enumerate() {
        if c.is_ascii_uppercase() && index > 0 {
            name.push('_');
        }
        name.push(c.to_ascii_uppercase());
    }
    name
}
