[package]
name = "rdlt-fuzz"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
bytes = "1.12.1"
libfuzzer-sys = "0.4.13"
rdlt-connector = { path = "../crates/rdlt-connector", default-features = false }

[[bin]]
name = "state_record"
path = "fuzz_targets/state_record.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
