//! The clause registry: every clause this crate certifies, by family, and the documentation
//! generated from it.

use std::fmt::Write as _;

use rdlt_connector::testing::{Clause, DESTINATION_CLAUSES, SOURCE_CLAUSES};

use crate::protocol::PROTOCOL_CLAUSES;

/// A family of clauses.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Family {
    /// The protocol's (`P`), which every connector meets whatever its role.
    Protocol,
    /// A source's (`S`).
    Source,
    /// A destination's (`D`).
    Destination,
}

impl Family {
    const ALL: [Self; 3] = [Self::Protocol, Self::Source, Self::Destination];

    /// Its clauses, in the order they are checked.
    pub fn clauses(self) -> &'static [Clause] {
        match self {
            Self::Protocol => PROTOCOL_CLAUSES,
            Self::Source => SOURCE_CLAUSES,
            Self::Destination => DESTINATION_CLAUSES,
        }
    }

    fn title(self) -> &'static str {
        match self {
            Self::Protocol => "Protocol (`P`)",
            Self::Source => "Source (`S`)",
            Self::Destination => "Destination (`D`)",
        }
    }
}

/// Every clause, by family.
pub fn clauses() -> impl Iterator<Item = (Family, &'static Clause)> {
    Family::ALL
        .into_iter()
        .flat_map(|family| family.clauses().iter().map(move |clause| (family, clause)))
}

/// The clauses' documentation, in Markdown: generated from the registry, so it never disagrees
/// with what is checked.
pub fn markdown() -> String {
    let mut text = String::from(
        "# Conformance clauses\n\nGenerated by `rdlt-certify --clauses`; do not edit.\n",
    );
    for family in Family::ALL {
        write!(
            text,
            "\n## {}\n\n| Clause | Statement |\n|---|---|\n",
            family.title()
        )
        .ok();
        for clause in family.clauses() {
            writeln!(text, "| `{}` | {} |", clause.id, clause.statement).ok();
        }
    }
    text
}
