//! The clause registry: every clause this crate certifies, by family, and the documentation
//! generated from it.

use std::fmt::Write as _;

use rdlt_connector::testing::{Clause, DESTINATION_CLAUSES, SOURCE_CLAUSES};

use crate::kill::KILL_CLAUSES;
use crate::protocol::PROTOCOL_CLAUSES;

/// A family of clauses.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Family {
    /// The protocol's (`P`), which every connector meets whatever its role.
    Protocol,
    /// A source's (`S`).
    Source,
    /// A destination's (`D`).
    Destination,
    /// A connector's killed as an engine loads through it (`K`).
    Kill,
}

impl Family {
    const ALL: [Self; 4] = [Self::Protocol, Self::Source, Self::Destination, Self::Kill];

    /// Its clauses, in the order they are checked.
    pub fn clauses(self) -> &'static [Clause] {
        match self {
            Self::Protocol => PROTOCOL_CLAUSES,
            Self::Source => SOURCE_CLAUSES,
            Self::Destination => DESTINATION_CLAUSES,
            Self::Kill => KILL_CLAUSES,
        }
    }

    fn title(self) -> &'static str {
        match self {
            Self::Protocol => "Protocol (`P`)",
            Self::Source => "Source (`S`)",
            Self::Destination => "Destination (`D`)",
            Self::Kill => "Kill (`K`)",
        }
    }
}

/// Every clause, by family.
pub fn clauses() -> impl Iterator<Item = (Family, &'static Clause)> {
    Family::ALL
        .into_iter()
        .flat_map(|family| family.clauses().iter().map(move |clause| (family, clause)))
}

/// The clauses' documentation, in Markdown: generated from the registry, so it never disagrees
/// with what is checked.
pub fn markdown() -> String {
    let mut text = String::from(PREFACE);
    for family in Family::ALL {
        write!(
            text,
            "\n## {}\n\n| Clause | Statement | Does not apply when |\n|---|---|---|\n",
            family.title()
        )
        .ok();
        for clause in family.clauses() {
            let unless = if clause.unless.is_empty() {
                "—"
            } else {
                clause.unless
            };
            writeln!(
                text,
                "| `{}` | {} | {unless} |",
                clause.id, clause.statement
            )
            .ok();
        }
    }
    text.push_str(LIMITS);
    text
}

/// What the documentation says before the clauses: how a clause fares, and what a report and
/// the binary's exit code make of it.
const PREFACE: &str = "\
# Conformance clauses

Generated by `rdlt-certify --clauses`; do not edit.

## Outcomes and verdicts

Each clause has one of four outcomes:

| Outcome | Report | Meaning |
|---|---|---|
| passed | `pass` | the connector was seen to meet the clause |
| failed | `FAIL` | the connector breaks the clause, for the reason given |
| inapplicable | `n/a` | the clause does not apply to what the connector declares: the tables \
below say when |
| unobserved | `skip` | the clause applies, yet what it requires was not seen: it neither passed \
nor failed |

A report's verdict follows from its outcomes:

| Verdict | When | Exit code |
|---|---|---|
| passed | no clause failed, none that applies went unobserved, and one passed at least | 0 |
| incomplete | no clause failed, yet one that applies was not observed, or none passed | 2 |
| failed | a clause failed | 1 |

The clauses a connector must pass are therefore those its declarations leave applicable: a \
connector cannot skip one by how it behaves, only by declaring less, and the engine uses of a \
connector only what it declares. `--require partial` exits 0 for an incomplete certification in \
which no clause failed and one passed; the report, and its JSON `verdict` and `passed`, say \
incomplete all the same. A clause is unobserved when nothing reads back what a destination \
published, when a source sends no checkpoint to resume or plan again from, when a read ends \
within its first credit, when no kill reaches the connector, or when what a source sends is \
more than certification holds: certify with a fixture that shows the behaviour.
";

/// What the documentation says after the clauses: what a certification bounds, and what it
/// cannot show.
const LIMITS: &str = "
## What certification bounds

- Every call has a deadline, each clause a bound on all its work (30 s a protocol clause, 600 s a \
source or destination clause, 300 s a kill clause unless `--kill-timeout` says), and `--timeout` \
bounds a whole run.
- A source clause holds at most 64 MiB and 1,048,576 rows of what its reads send, all its reads \
together, and renders at most 64 MiB of text; a kill clause loads at most 100,000 rows and \
64 MiB. A source that holds more leaves the clause unobserved.
- A read-back holds at most 10,000 rows (100,000 for the kill clause) of flat columns, plain, \
dictionary or run-end encoded, that take at most 16 MiB once each row holds its own value, and at \
most 64 MiB on the wire. A destination that reads back more, or other columns, fails the clause.
- A reason is at most 2048 bytes, and quotes at most the first eight rows of those it counts.
- A kill clause passes only when a kill landed: the host saw a connection to the connector end \
after the kill, which a spawned connector's does once every process of its group is gone.
- `P-CREDIT` watches a read whose credit is spent for four seconds, granting a byte three times: \
a source that ignores credit and sends less often than that is not told from one that waits.

## What certification cannot show

- A read-back is the destination's own account of what it published. The clauses that compare \
it with what was committed certify a destination against that account; a probe that reads the \
store itself is the stronger check.
- A connector can tell a certification from an engine's load: by the tables and pipelines \
certification names `certify_…`, the read-back and acknowledged features it offers, and the \
calls it makes. A connector built to pass keeps the clauses while it is certified and may break \
them later. Certification finds the defects of a connector that does not hide them; it is no \
control against one that does. The engine's own limits, deadlines and confinement are.
";
