//! The clause registry: every clause this crate certifies, by family, and the documentation
//! generated from it.

use std::fmt::Write as _;

use rdlt_connector::testing::{Clause, DESTINATION_CLAUSES, SOURCE_CLAUSES};

use crate::kill::KILL_CLAUSES;
use crate::protocol::PROTOCOL_CLAUSES;

/// A family of clauses.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Family {
    /// The protocol's (`P`), which every connector meets whatever its role.
    Protocol,
    /// A source's (`S`).
    Source,
    /// A destination's (`D`).
    Destination,
    /// A connector's killed as an engine loads through it (`K`).
    Kill,
}

impl Family {
    const ALL: [Self; 4] = [Self::Protocol, Self::Source, Self::Destination, Self::Kill];

    /// Its clauses, in the order they are checked.
    pub fn clauses(self) -> &'static [Clause] {
        match self {
            Self::Protocol => PROTOCOL_CLAUSES,
            Self::Source => SOURCE_CLAUSES,
            Self::Destination => DESTINATION_CLAUSES,
            Self::Kill => KILL_CLAUSES,
        }
    }

    fn title(self) -> &'static str {
        match self {
            Self::Protocol => "Protocol (`P`)",
            Self::Source => "Source (`S`)",
            Self::Destination => "Destination (`D`)",
            Self::Kill => "Kill (`K`)",
        }
    }
}

/// Every clause, by family.
pub fn clauses() -> impl Iterator<Item = (Family, &'static Clause)> {
    Family::ALL
        .into_iter()
        .flat_map(|family| family.clauses().iter().map(move |clause| (family, clause)))
}

/// The clauses' documentation, in Markdown: generated from the registry, so it never disagrees
/// with what is checked.
pub fn markdown() -> String {
    let mut text = String::from(PREFACE);
    for family in Family::ALL {
        write!(
            text,
            "\n## {}\n\n| Clause | Statement | Does not apply when |\n|---|---|---|\n",
            family.title()
        )
        .ok();
        for clause in family.clauses() {
            let unless = if clause.unless.is_empty() {
                "—"
            } else {
                clause.unless
            };
            writeln!(
                text,
                "| `{}` | {} | {unless} |",
                clause.id, clause.statement
            )
            .ok();
        }
    }
    text.push_str(LIMITS);
    text
}

/// What the documentation says before the clauses: how a clause fares, and what a report and
/// the binary's exit code make of it.
const PREFACE: &str = "\
# Conformance clauses

Generated by `rdlt-certify --clauses`; do not edit.

## Outcomes and verdicts

Each clause has one of four outcomes:

| Outcome | Report | Meaning |
|---|---|---|
| passed | `pass` | the connector was seen to meet the clause |
| failed | `FAIL` | the connector breaks the clause, for the reason given |
| inapplicable | `n/a` | the clause does not apply to what the connector declares: the tables \
below say when |
| unobserved | `skip` | the clause applies, yet what it requires was not seen: it neither passed \
nor failed |

A report's verdict follows from its outcomes:

| Verdict | When | Exit code |
|---|---|---|
| passed | no clause failed, none that applies went unobserved, and one passed at least | 0 |
| incomplete | no clause failed, yet one that applies was not observed, or none passed | 2 |
| failed | a clause failed | 1 |

The clauses a connector must pass are therefore those its declarations leave applicable: a \
connector cannot skip one by how it behaves, only by declaring less, and the engine uses of a \
connector only what it declares. `--require partial` exits 0 for an incomplete certification in \
which no clause failed and one passed; the report, and its JSON `verdict` and `passed`, say \
incomplete all the same. A clause is unobserved when nothing reads back what a destination \
published, when a source sends no checkpoint to resume or plan again from, when a read ends \
within its first credit, when no kill reaches the connector, or when what a source sends is \
more than certification holds: certify with a fixture that shows the behaviour.

A kill clause that passed says beside its `pass`, and as `note` in JSON, what it passed on: \
`killed`, a connection ended with a process a kill ended, or `cut`, kills cut the connection of \
a connector the host did not start, and no process was seen to stop.

`P-CREDIT`'s pass says beside its `pass`, and as `note` in JSON, the watch it ran under when \
`--credit-watch` chose one other than a second.

## Exit codes

| Code | When |
|---|---|
| 0 | every role certified passed, or, with `--require partial`, none failed and each passed a \
clause |
| 1 | a clause failed, or the connector serves none of the roles asked |
| 2 | no clause failed, yet a role's certification is incomplete |
| 64 | the command line was wrong: an option, the configuration's JSON, the endpoint, or a \
`--timeout` further ahead than the clock holds |
| 74 | a file named could not be read, the connector's binary is missing or not executable, or \
a connector the certification spawned was not seen to stop |
| 130, 143, 129, 131 | the certification was interrupted (`SIGINT`), asked to terminate \
(`SIGTERM`), hung up on (`SIGHUP`) or asked to quit (`SIGQUIT`): the connectors it spawned are \
stopped first, and killed at once on a second signal |

A certification cut at its timeout reports what it saw: the clauses already checked keep their \
outcomes, the clause it was cut in fails, as does the first clause of a role it never started, \
and the clauses after are not observed, so it exits 1.
";

/// What the documentation says after the clauses: what a certification bounds, and what it
/// cannot show.
const LIMITS: &str = "
## What certification bounds

- Every call has a deadline, each clause a bound on all its work (30 s a protocol clause, 600 s a \
source or destination clause, 300 s a kill clause unless `--kill-timeout` says). A whole run \
takes at most an hour unless `--timeout` says otherwise or `--no-timeout` lifts the bound; the \
clause being checked then fails, and nothing more is started.
- A source clause holds at most 64 MiB and 1,048,576 rows of what its reads send, all its reads \
together, and renders at most 64 MiB of text; a kill clause loads at most 100,000 rows and \
64 MiB. A source that holds more leaves the clause unobserved. A JSON push is charged a row for \
each record its text holds before any is parsed, and a record of more than 1 MiB leaves the \
clause unobserved.
- `S-RESUME` resumes from every checkpoint of a read that sent five at most, and else from \
five spread from the first to the last: a resume that is wrong only from a checkpoint between \
them is not caught. It compares the pushes of a resumed read only while their batches, with the \
first read's, expand to 64 MiB at most once each row holds its own value; beyond that it is \
unobserved.
- A read-back holds at most 10,000 rows (100,000 for the kill clause) of flat columns, plain, \
dictionary or run-end encoded, that take at most 16 MiB once each row holds its own value, and at \
most 64 MiB on the wire. A column is read only as the kind it was written as, or a kind that \
holds the same values: integers as 64-bit integers, text as any text, bytes as any bytes, an \
instant as its count. A destination that reads back more, or other columns, fails the clause.
- A reason is at most 2048 bytes, and quotes at most the first eight rows of those it counts.
- A kill clause passes only when a kill landed: the host saw a connection to the connector end \
after the kill. A spawned connector's ends once no process holds its other end, which a kill of \
its process group brings about unless a process left the group and holds it. The connection of a \
connector reached at an endpoint, or served in process, is cut by the host, which proves no \
process stopped: the report notes which was seen.
- A kill clause loads in a mode the connector declares: a destination in the first of append, \
merge and replace it writes, a source each stream in the first of incremental, full and change \
reads it serves. A destination that keeps history alone leaves `K-DESTINATION` unobserved, and \
one whose identifiers are shorter than the names `D-NAMES` writes leaves that unobserved.
- A spawned connector leads a process group the certifier stops, then kills, when the \
certification ends, is cut at its timeout, panics, or hears a signal. A member that left the \
group is not reached, and neither is anything when the certifier is killed outright.
- `P-CREDIT` watches a read whose credit is spent for four seconds, granting a byte three times, \
or four times the watch `--credit-watch` chooses: a source that ignores credit and sends less \
often than that is not told from one that waits.

## What certification cannot show

- A read-back is the destination's own account of what it published. The clauses that compare \
it with what was committed certify a destination against that account; a probe that reads the \
store itself is the stronger check.
- A connector can tell a certification from an engine's load: by the tables and pipelines \
certification names `certify_…`, the read-back and acknowledged features it offers, and the \
calls it makes. A connector built to pass keeps the clauses while it is certified and may break \
them later. Certification finds the defects of a connector that does not hide them; it is no \
control against one that does. The engine's own limits, deadlines and confinement are.
";
