# Generated by grpcio-tools==1.83.0 from rdlt_connector_v0.proto — do not edit; tools/check-python-stubs.sh verifies.
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rdlt_connector_v0_pb2 as rdlt__connector__v0__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rdlt_connector_v0_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConnectorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Handshake = channel.unary_unary(
                '/rdlt.connector.v0.Connector/Handshake',
                request_serializer=rdlt__connector__v0__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=rdlt__connector__v0__pb2.HandshakeReply.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/rdlt.connector.v0.Connector/Check',
                request_serializer=rdlt__connector__v0__pb2.CheckRequest.SerializeToString,
                response_deserializer=rdlt__connector__v0__pb2.CheckReply.FromString,
                _registered_method=True)
        self.Spec = channel.unary_unary(
                '/rdlt.connector.v0.Connector/Spec',
                request_serializer=rdlt__connector__v0__pb2.SpecRequest.SerializeToString,
                response_deserializer=rdlt__connector__v0__pb2.SpecReply.FromString,
                _registered_method=True)


class ConnectorServicer:
    """Missing associated documentation comment in .proto file."""

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Spec(self, request, context):
        """Config-free static identity: answers BEFORE any handshake —
        it carries no session state, so the pre-handshake refusal does not
        apply to it. spec_json is ConnectorSpec (name, version,
        config_schema), served from the connector's statics alone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=rdlt__connector__v0__pb2.HandshakeRequest.FromString,
                    response_serializer=rdlt__connector__v0__pb2.HandshakeReply.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=rdlt__connector__v0__pb2.CheckRequest.FromString,
                    response_serializer=rdlt__connector__v0__pb2.CheckReply.SerializeToString,
            ),
            'Spec': grpc.unary_unary_rpc_method_handler(
                    servicer.Spec,
                    request_deserializer=rdlt__connector__v0__pb2.SpecRequest.FromString,
                    response_serializer=rdlt__connector__v0__pb2.SpecReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rdlt.connector.v0.Connector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rdlt.connector.v0.Connector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Connector:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdlt.connector.v0.Connector/Handshake',
            rdlt__connector__v0__pb2.HandshakeRequest.SerializeToString,
            rdlt__connector__v0__pb2.HandshakeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdlt.connector.v0.Connector/Check',
            rdlt__connector__v0__pb2.CheckRequest.SerializeToString,
            rdlt__connector__v0__pb2.CheckReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Spec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdlt.connector.v0.Connector/Spec',
            rdlt__connector__v0__pb2.SpecRequest.SerializeToString,
            rdlt__connector__v0__pb2.SpecReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SourceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Streams = channel.unary_unary(
                '/rdlt.connector.v0.SourceService/Streams',
                request_serializer=rdlt__connector__v0__pb2.StreamsRequest.SerializeToString,
                response_deserializer=rdlt__connector__v0__pb2.StreamsReply.FromString,
                _registered_method=True)
        self.Read = channel.unary_stream(
                '/rdlt.connector.v0.SourceService/Read',
                request_serializer=rdlt__connector__v0__pb2.ReadRequest.SerializeToString,
                response_deserializer=rdlt__connector__v0__pb2.ReadFrame.FromString,
                _registered_method=True)


class SourceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Streams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SourceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Streams': grpc.unary_unary_rpc_method_handler(
                    servicer.Streams,
                    request_deserializer=rdlt__connector__v0__pb2.StreamsRequest.FromString,
                    response_serializer=rdlt__connector__v0__pb2.StreamsReply.SerializeToString,
            ),
            'Read': grpc.unary_stream_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=rdlt__connector__v0__pb2.ReadRequest.FromString,
                    response_serializer=rdlt__connector__v0__pb2.ReadFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rdlt.connector.v0.SourceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rdlt.connector.v0.SourceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SourceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Streams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rdlt.connector.v0.SourceService/Streams',
            rdlt__connector__v0__pb2.StreamsRequest.SerializeToString,
            rdlt__connector__v0__pb2.StreamsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rdlt.connector.v0.SourceService/Read',
            rdlt__connector__v0__pb2.ReadRequest.SerializeToString,
            rdlt__connector__v0__pb2.ReadFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DestinationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.OpenSession = channel.stream_stream(
                '/rdlt.connector.v0.DestinationService/OpenSession',
                request_serializer=rdlt__connector__v0__pb2.SessionRequest.SerializeToString,
                response_deserializer=rdlt__connector__v0__pb2.SessionReply.FromString,
                _registered_method=True)


class DestinationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def OpenSession(self, request_iterator, context):
        """The client MUST read replies concurrently with sending requests,
        not write-everything-then-read: this server's reply channel is
        BOUNDED (the sdk's REPLY_CHANNEL_BUDGET) and interleaves
        PartClosedEvent notifications with request replies, so a client
        that defers reading until every request is sent can wedge itself
        against a full h2 flow-control window once enough replies queue up
        unread on the server side.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DestinationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'OpenSession': grpc.stream_stream_rpc_method_handler(
                    servicer.OpenSession,
                    request_deserializer=rdlt__connector__v0__pb2.SessionRequest.FromString,
                    response_serializer=rdlt__connector__v0__pb2.SessionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rdlt.connector.v0.DestinationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rdlt.connector.v0.DestinationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DestinationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def OpenSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/rdlt.connector.v0.DestinationService/OpenSession',
            rdlt__connector__v0__pb2.SessionRequest.SerializeToString,
            rdlt__connector__v0__pb2.SessionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
