#!/usr/bin/env bash
# check-python-stubs.sh — the vendored-stub drift gate for the Python
# proof connector. The connector vendors its generated grpc/protobuf
# stubs (a pip-less checkout must still be readable, and generation
# must be pinned, not floating); this script proves the vendored pair
# still matches the proto: it regenerates both files with the EXACT
# generator the stub headers name, into a tempdir, and diffs. Drift
# exits 1 with the regeneration commands spelled out.
#
# The generator pin's source of truth is the vendored stubs' own first
# line (`# Generated by grpcio-tools==X ...`), so the check always
# regenerates with what the tree claims was used.
set -euo pipefail

repo="$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)"
pkg="$repo/connectors/python/rdlt-connector-pyjsonl"
proto_dir="$repo/crates/rdlt-connector-protocol/proto"
pb2="$pkg/rdlt_connector_v1_pb2.py"
pb2_grpc="$pkg/rdlt_connector_v1_pb2_grpc.py"

command -v python3 >/dev/null 2>&1 || {
    echo "check-python-stubs: python3 is required" >&2
    exit 1
}

header="$(head -n 1 "$pb2")"
pin="$(printf '%s\n' "$header" | grep -oE 'grpcio-tools==[0-9][0-9A-Za-z.]*')" || {
    echo "check-python-stubs: $pb2 does not start with the pinned-generator header" >&2
    exit 1
}
if [ "$header" != "$(head -n 1 "$pb2_grpc")" ]; then
    echo "check-python-stubs: the two vendored stubs carry different headers" >&2
    exit 1
fi

# The generator venv, cached under target/ and keyed on the pin — a
# changed pin rebuilds it, an intact one is reused as-is. A broken
# venv (pip failing, python missing from it) fails loudly.
venv="$repo/target/py-stubgen-venv"
if [ ! -x "$venv/bin/python" ] || [ "$(cat "$venv/.pin" 2>/dev/null || true)" != "$pin" ]; then
    rm -rf "$venv"
    python3 -m venv "$venv"
    "$venv/bin/pip" install --quiet "$pin"
    printf '%s' "$pin" >"$venv/.pin"
fi

mkdir -p "${TMPDIR:-/tmp}"
tmp="$(mktemp -d "${TMPDIR:-/tmp}/rdlt-stubcheck.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT

"$venv/bin/python" -m grpc_tools.protoc -I "$proto_dir" \
    --python_out="$tmp" --grpc_python_out="$tmp" rdlt_connector_v1.proto

drift=0
for name in rdlt_connector_v1_pb2.py rdlt_connector_v1_pb2_grpc.py; do
    { printf '%s\n' "$header"; cat "$tmp/$name"; } >"$tmp/$name.headed"
    if ! diff -q "$tmp/$name.headed" "$pkg/$name" >/dev/null; then
        echo "check-python-stubs: $name drifts from the proto" >&2
        drift=1
    fi
done

if [ "$drift" -ne 0 ]; then
    cat >&2 <<EOF
check-python-stubs: the vendored stubs no longer match
crates/rdlt-connector-protocol/proto/rdlt_connector_v1.proto.
Regenerate them (from the repo root) with:

  python3 -m venv target/py-stubgen-venv
  target/py-stubgen-venv/bin/pip install '$pin'
  target/py-stubgen-venv/bin/python -m grpc_tools.protoc \\
      -I crates/rdlt-connector-protocol/proto \\
      --python_out=connectors/python/rdlt-connector-pyjsonl \\
      --grpc_python_out=connectors/python/rdlt-connector-pyjsonl \\
      rdlt_connector_v1.proto

then re-prepend this exact header line to BOTH generated files
(and update its pin if the generator moved):

  $header
EOF
    exit 1
fi
echo "check-python-stubs: vendored stubs match rdlt_connector_v1.proto ($pin)"
