//! RESULTS.md table generation (contract BH7): number tables regenerate from
//! artifacts between explicit markers; the hand-written narrative outside the
//! markers is preserved byte-for-byte. No markers → refusal, never guessing.

use std::path::Path;

use crate::artifact::{Artifact, CompetitorSide};
use crate::cells::{Bar, BarKind, Cell};
use crate::{BenchError, Result};

pub fn begin_marker(section: &str) -> String {
    format!("<!-- rdlt-bench:BEGIN {section} -->")
}
pub fn end_marker(section: &str) -> String {
    format!("<!-- rdlt-bench:END {section} -->")
}

fn fmt_ms(ms: f64) -> String {
    if ms >= 1000.0 { format!("{:.2} s", ms / 1000.0) } else { format!("{ms:.1} ms") }
}

fn fmt_opt<T>(v: Option<T>, f: impl Fn(T) -> String) -> String {
    v.map_or_else(|| "—".to_owned(), f)
}

fn bar_target(bar: Option<&Bar>) -> String {
    match bar.map(|b| &b.kind) {
        Some(BarKind::RatioVs { min_ratio, .. }) => format!("≥ {min_ratio}×"),
        Some(BarKind::AbsoluteMs { max_ms }) => format!("≤ {max_ms} ms abs"),
        Some(BarKind::RssRatioVs { max_rss_ratio, .. }) => format!("≤ 1/{:.0}", 1.0 / max_rss_ratio),
        None => "—".into(),
    }
}

/// One table row per artifact: the full BH3 metric set + baseline ratio.
fn table_for(artifacts: &[&Artifact], bars: &[Bar]) -> String {
    let mut out = String::new();
    out.push_str(
        "| Cell | Class | rdlt median | vs baseline | Target | rows/s | MB/s | peak CPU | peak RSS |\n",
    );
    out.push_str("|---|---|---|---|---|---|---|---|---|\n");
    for artifact in artifacts {
        let bar = bars.iter().find(|b| b.cell == artifact.cell_id);
        let baseline = artifact.competitors.iter().next().map(|(id, side)| match side {
            CompetitorSide::Ok { median_ms, ratio_vs_rdlt, .. } => format!(
                "**{:.1}×** ({id}: {})",
                ratio_vs_rdlt.unwrap_or(median_ms / artifact.rdlt.median_ms),
                fmt_ms(*median_ms)
            ),
            CompetitorSide::Missing { reason } => format!("MISSING ({reason})"),
        });
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
            artifact.cell_id,
            artifact.class,
            fmt_ms(artifact.rdlt.median_ms),
            baseline.unwrap_or_else(|| "—".into()),
            bar_target(bar),
            fmt_opt(artifact.rdlt.rows_per_s, |v| format!("{:.0}", v)),
            fmt_opt(artifact.rdlt.mb_per_s, |v| format!("{v:.1}")),
            fmt_opt(artifact.rdlt.cpu.peak_util, |v| format!("{:.0}%", v * 100.0)),
            fmt_opt(artifact.rdlt.rss.peak_bytes, |v| format!("{} MB", v >> 20)),
        ));
    }
    let dates: std::collections::BTreeSet<&str> =
        artifacts.iter().map(|a| a.recorded_at.as_str()).collect();
    let pins: std::collections::BTreeSet<&str> = artifacts
        .iter()
        .filter_map(|a| a.fingerprint.competitor_pin.as_deref())
        .collect();
    out.push_str(&format!(
        "\n_Generated by `rdlt-bench report` from committed artifacts (recorded {}{})._\n",
        dates.into_iter().collect::<Vec<_>>().join(", "),
        if pins.is_empty() {
            String::new()
        } else {
            format!("; {}", pins.into_iter().collect::<Vec<_>>().join(", "))
        }
    ));
    out
}

/// Splice `body` between the section's markers. Everything outside the
/// markers — the narrative — is preserved byte-for-byte.
pub fn splice(results_md: &str, section: &str, body: &str) -> Result<String> {
    let begin = begin_marker(section);
    let end = end_marker(section);
    let start = results_md.find(&begin).ok_or_else(|| {
        BenchError(format!(
            "RESULTS.md has no `{begin}` marker — insert the marker pair where the {section} table belongs"
        ))
    })?;
    let after_begin = start + begin.len();
    let end_at = results_md[after_begin..]
        .find(&end)
        .map(|i| after_begin + i)
        .ok_or_else(|| BenchError(format!("RESULTS.md has `{begin}` but no `{end}`")))?;
    let mut out = String::with_capacity(results_md.len() + body.len());
    out.push_str(&results_md[..after_begin]);
    out.push('\n');
    out.push_str(body.trim_end());
    out.push('\n');
    out.push_str(&results_md[end_at..]);
    Ok(out)
}

/// Regenerate every suite section present in RESULTS.md from the artifacts on
/// disk. Suites without a marker pair are skipped ONLY if none of their cells
/// have artifacts; a suite with artifacts but no markers is an error (no
/// silent truncation).
pub fn regenerate(
    results_md_path: &Path,
    cells: &[Cell],
    bars: &[Bar],
    results_dir: &Path,
) -> Result<Vec<String>> {
    let mut content = std::fs::read_to_string(results_md_path)
        .map_err(|e| BenchError(format!("reading {}: {e}", results_md_path.display())))?;
    let mut suites: Vec<&str> = cells.iter().map(|c| c.suite.as_str()).collect();
    suites.sort_unstable();
    suites.dedup();

    let mut updated = Vec::new();
    for suite in suites {
        let artifacts: Vec<Artifact> = cells
            .iter()
            .filter(|c| c.suite == suite)
            .filter_map(|c| crate::artifact::read(results_dir, &c.id).ok())
            .collect();
        if artifacts.is_empty() {
            continue;
        }
        let refs: Vec<&Artifact> = artifacts.iter().collect();
        let body = table_for(&refs, bars);
        if !content.contains(&begin_marker(suite)) {
            return Err(BenchError(format!(
                "suite `{suite}` has artifacts but RESULTS.md has no `{}` marker",
                begin_marker(suite)
            )));
        }
        content = splice(&content, suite, &body)?;
        updated.push(suite.to_owned());
    }
    std::fs::write(results_md_path, content)?;
    Ok(updated)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cells::Class;

    const DOC: &str = "# Results\n\nNarrative ABOVE — every byte sacred.\n\n<!-- rdlt-bench:BEGIN e2e -->\nold table\n<!-- rdlt-bench:END e2e -->\n\nNarrative BELOW — history, policy notes.\n";

    #[test]
    fn splice_replaces_only_between_markers() {
        let out = splice(DOC, "e2e", "| new |").unwrap();
        assert!(out.contains("Narrative ABOVE — every byte sacred."));
        assert!(out.contains("Narrative BELOW — history, policy notes."));
        assert!(out.contains("| new |"));
        assert!(!out.contains("old table"));
        // idempotent: splicing the same body again changes nothing
        assert_eq!(splice(&out, "e2e", "| new |").unwrap(), out);
    }

    #[test]
    fn narrative_is_byte_identical_outside_markers() {
        let out = splice(DOC, "e2e", "X").unwrap();
        let begin = begin_marker("e2e");
        let end = end_marker("e2e");
        let (before_in, after_in) =
            (DOC.split(&begin).next().unwrap(), DOC.split(&end).nth(1).unwrap());
        let (before_out, after_out) =
            (out.split(&begin).next().unwrap(), out.split(&end).nth(1).unwrap());
        assert_eq!(before_in, before_out);
        assert_eq!(after_in, after_out);
    }

    #[test]
    fn missing_markers_are_a_refusal_not_a_guess() {
        let err = splice("no markers here", "e2e", "X").unwrap_err().to_string();
        assert!(err.contains("BEGIN e2e"), "{err}");
        let err2 = splice("<!-- rdlt-bench:BEGIN e2e -->", "e2e", "X").unwrap_err().to_string();
        assert!(err2.contains("no `<!-- rdlt-bench:END e2e -->`"), "{err2}");
    }

    #[test]
    fn table_includes_missing_baselines_loudly() {
        let mut artifact = crate::artifact::tests::minimal("loud-cell", Class::Scoreboard);
        artifact
            .competitors
            .insert("dlt-pyarrow".into(), CompetitorSide::Missing { reason: "image not built".into() });
        let table = table_for(&[&artifact], &[]);
        assert!(table.contains("MISSING (image not built)"), "{table}");
        assert!(table.contains("loud-cell"), "{table}");
    }
}
